version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  server: 
    build: ../server
    volumes:
      - .:/app/server
      - /app/server/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: yarn start:dev
    depends_on:
      - mongodb

  client: 
    build: ../client
    volumes:
      - .:/app/client
      - /app/client/node_modules
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    command: yarn dev
    depends_on:
      - server

volumes:
  mongodb_data_container: